<?php
/**
 * RcpTwilioNotifier: RcpTwilioNotifier\Models\SendAttempt class
 *
 * @package WordPress
 * @subpackage RcpTwilioNotifier\Models
 */

namespace RcpTwilioNotifier\Models;

/**
 * An attempt to message a Member.
 */
class SendAttempt {

	/**
	 * The messaged Member.
	 *
	 * @var Member
	 */
	public $recipient;

	/**
	 * The status of the attempt.
	 *
	 * @var 'success'|'failed'
	 */
	public $status;

	/**
	 * The attempt's timestamp.
	 *
	 * @var int
	 */
	public $timestamp;

	/**
	 * The error, if the attempt failed.
	 *
	 * @var null|string
	 */
	public $error;

	/**
	 * Create internal values.
	 *
	 * @param Member             $recipient  Recipient.
	 * @param 'success'|'failed' $status     Status.
	 * @param int                $timestamp  Timestamp.
	 * @param null|string        $error      Error message.
	 */
	public function __construct( $recipient, $status, $timestamp, $error = null ) {
		$this->recipient = $recipient;
		$this->status = $status;
		$this->timestamp = $timestamp;
		$this->error = $error;
	}

	/**
	 * Create an array representation of a SendAttempt.
	 *
	 * @return array
	 */
	public function convert_to_array() {
		$send_attempt = array(
			'recipient' => $this->recipient,
			'status'    => $this->status,
			'timestamp' => $this->timestamp,
		);

		if ( ! null === $this->error ) {
			$send_attempt['error'] = $this->error;
		}

		return $send_attempt;
	}

	/**
	 * Create a new SendAttempt from an array generated by the `convert_to_array` method.
	 *
	 * @param array $send_attempt {
	 *     Required. The send attempt as an array.
	 *
	 *     @type Member             $recipient  Recipient.
	 *     @type 'success'|'failed' $status     Status.
	 *     @type int                $timestamp  Timestamp.
	 *     @type null|string        $error      Error message. Optional.
	 * }
	 *
	 * @return SendAttempt
	 */
	public static function create_from_array( $send_attempt ) {
		if ( isset( $send_attempt['error'] ) ) {
			return new self(
				$send_attempt['recipient'],
				$send_attempt['status'],
				$send_attempt['timestamp'],
				$send_attempt['error']
			);
		}

		return new self(
			$send_attempt['recipient'],
			$send_attempt['status'],
			$send_attempt['timestamp']
		);
	}

}
